dist: xenial
language: python

cache:
  - pip

services:
  - docker

#branches:
#  only:
#    - master
#    # Build commits tagged with release version
#    - /^v\d+\.\d+\.\d+$/

env:
  global:
    - UNITTEST_QUIET=1
    # - UNITTEST_SKIP_POSTGESQL=1
    # - UNITTEST_SKIP_S3=1
    - UNITTEST_SKIP_B2=1
    - UNITTEST_SKIP_NBD=1

python:
  - 3.6
  - 3.7
  - nightly

matrix:
  allow_failures:
    - python: nightly

stages:
  - test
  - push

before_install:
  - curl --retry 5 -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - travis_retry sudo apt-get update
  - travis_retry sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  - docker version

install:
  - travis_retry pip install --upgrade setuptools pip
  - travis_retry pip install '.[s3,b2,compression,readcache,dev,doc]'

script:
  - pip freeze
  - make -C tests/minio-setup up
  - make -C tests/postgresql-setup up
  - python -m unittest discover -v -t src -s src/benji/tests
  - python setup.py sdist
  - make -C tests/minio-setup down
  - make -C tests/postgresql-setup down

jobs:
  include:
    - stage: test
      install:
        - travis_retry pip install --upgrade setuptools pip
      script:
        - SKIP_DOCKER_PUSH=1 DOCKER_BUILDKIT=0 VERSION_VARIANT=miniver DOCKERFILE_PATH=images/benji/Dockerfile maint-scripts/docker-build
        - SKIP_DOCKER_PUSH=1 DOCKER_BUILDKIT=0 VERSION_VARIANT=miniver DOCKERFILE_PATH=images/benji-k8s/Dockerfile maint-scripts/docker-build
    - stage: test
      before_install: skip
      install:
        - HELM_VERSION=2.12.3
        - curl --retry 5 -sLO https://storage.googleapis.com/kubernetes-helm/helm-v$HELM_VERSION-linux-amd64.tar.gz
        - tar --strip-components=1 -xzvvf helm-v$HELM_VERSION-linux-amd64.tar.gz linux-amd64/helm
        - rm -f helm-v$HELM_VERSION-linux-amd64.tar.gz
        - chmod a+x helm
      script:
        - ./helm lint charts/benji-k8s
    - stage: push
      env:
        - secure: 'FQTT5peY8YF1H9E0Xp5OHgdN15sAjFw4M++k5MJisihpFDSrBoVP9hdDLht/QmJiYERXZWwWp4+kHsBwti+IEcj9cgnalZ9FLHLZpuRPaRpPKaPAoSFH/hHCq8PsrzbubGeqEDFbT6FzChmwRCvuMy5WVga8PseKbB3icEfqbp7+tN8s6wdPw0yjxycWj1KJs0DiATG+qVL8ItRi74Lda7RSSUOoXV/VdYdoTf3Whx6vT3ztSpJtt+XP/khZI+/n5asvTlcIH2xx8eTiqxljE2mAC281uo21nkrEhoOLRYhBI5KKNSUquGIS36ZOdOTNdpH868yF0fELDbVf4j1NH+T1msT1sCJvoenhBOqJeHag5eI92N9FPKvIlk3uwD9S1LE+eTE2JqS+3OFzjwT+6nCGCfIxkz/Ql7kyhgt1ihOa/VVLXLhCyYm1LRpVcpDEeAE1ThQ1Gw8BKL6Xd4Es8Rzqeff8wy68tR0FAuMlkQiByqQWtaOHfcQyu0fduM4rcKtUGpNbWCwty1AwtlPsveikM4AMFP4OJnjSsXsNjzRVtNvZ0aRt6zpWm5XkTmIOunB/x6SVI/0n8l3b+azBkhP2MBcCspIJ43Hg/VcmCEqrZi9IoDFU9ILJ7T6k3pm4q0K7PvK9nd43v112r7AC7lf7cNTrUmFFtVwKY+JcnXg='
        - secure: 'Ag+33Rwe400cSj8uKVsvkV+N+/hG0oAeLZsu/bOIyxyBj6XSiykQUjsQO7JzDJgGYagTMo8B0TfsOGGHsDlPr+nSCBbI8lR7mFl/zcBLT2KtJWA/RACwgRmJX34IwnLBu2bsHdRCMHUwVjO3X+sFQ6nTdU8PtCoV8LwMF2NYDciiupUmoBSvhOMcEmg5NrylyL9YBVpLIcQskrJ/b+7xpBPeUAVVxcTrx80rAgnkE81YkC998+85ZJZNaM+3lYwhi1h6XVKM8tjobGfVSpdFnrwmDjDaZgisR6LOue6RiFsKn12yhUZjDc+C0SNatTajpqIMWONE1kPW89EiJ+NRzbqEVr15ByUccWerVATkkqXzvPv3D+PlfeygmjTBMIdTqkAsF3C76zC3G6bZR9QerxeO/5v7Jv/C+sPJ/Q8UrLs9WfIAQgYSwRrQ5GFC2K/814SI3/kxk/oJU8SXgd+jj4KfxvgQFn8cIG8Jkne/f/oIKf0kGyYWqf+cH+XDjF7P/EkRnCV3+0YLEwQaJx9/AcTc8i8CY3uVQ0jLlKOBJhKXoXbqt6VLOOYDquRjzyOe2tQUJXXZSmbJEtzzkaf9zY5v7oQT8pVWXJOf7Qvd3UjRc2Qpu7v7k4ba9jEBQJk/+zdmn1NX5PuUix5d79cdFoqr5ADHGgw05ExgTP0OP1Y='
      install: skip
      script:
        - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
        - DOCKER_BUILDKIT=0 VERSION_VARIANT=miniver DOCKERFILE_PATH=images/benji/Dockerfile maint-scripts/docker-build
        - DOCKER_BUILDKIT=0 VERSION_VARIANT=miniver DOCKERFILE_PATH=images/benji-k8s/Dockerfile maint-scripts/docker-build
