dist: xenial
language: python

services:
  - docker

python:
  - 3.6
  - 3.7
  - nightly

branches:
  only:
    - master

env:
  global:
    - UNITTEST_QUIET=1
    # - UNITTEST_SKIP_POSTGESQL=1
    # - UNITTEST_SKIP_S3=1
    - UNITTEST_SKIP_B2=1
    - UNITTEST_SKIP_NBD=1

matrix:
  allow_failures:
    - python: nightly

cache:
  - pip

before_install:
  - uname -a
  - lsb_release -a
  - printenv
  - virtualenv --version
  - python --version
  - docker version
  - travis_retry pip install --upgrade setuptools
  - travis_retry pip install --upgrade pip

install:
  - travis_retry pip install '.[s3,b2,compression,readcache,dev]'
  - travis_retry pip install -r requirements_docs.txt

before_script:
  - pip freeze
  - make -C tests/minio-setup up
  - make -C tests/postgresql-setup up

script:
  - python -m unittest discover -v -t src -s src/benji/tests
  - DOCKERFILE_PATH=images/benji/Dockerfile maint-scripts/docker-build
  - DOCKERFILE_PATH=images/benji-k8s/Dockerfile maint-scripts/docker-build
  - python setup.py sdist

after_success:
  - 'docker images | grep elementalnet'
