dist: xenial
language: python

cache:
  - pip

services:
  - docker

branches:
  only:
    - master

env:
  global:
    - UNITTEST_QUIET=1
    # - UNITTEST_SKIP_POSTGESQL=1
    # - UNITTEST_SKIP_S3=1
    - UNITTEST_SKIP_B2=1
    - UNITTEST_SKIP_NBD=1

python:
  - 3.6
  - 3.7
  - nightly

matrix:
  allow_failures:
    - python: nightly

stages:
  - test
  - push

before_install:
  - uname -a
  - lsb_release -a
  - virtualenv --version
  - python --version
  - docker version

install:
  - travis_retry pip install --upgrade setuptools pip
  - travis_retry pip install '.[s3,b2,compression,readcache,dev]'
  - travis_retry pip install -r requirements_docs.txt

script:
  - pip freeze
  - make -C tests/minio-setup up
  - make -C tests/postgresql-setup up
  - python -m unittest discover -v -t src -s src/benji/tests
  - python setup.py sdist
  - make -C tests/minio-setup down
  - make -C tests/postgresql-setup down

jobs:
  include:
    - stage: test
      install:
        - travis_retry pip install --upgrade setuptools pip
      script:
        - SKIP_DOCKER_PUSH=1 GIT_PEP440_VERSION_VARIANT=miniver DOCKERFILE_PATH=images/benji/Dockerfile maint-scripts/docker-build
        - SKIP_DOCKER_PUSH=1 GIT_PEP440_VERSION_VARIANT=miniver DOCKERFILE_PATH=images/benji-k8s/Dockerfile maint-scripts/docker-build
    - stage: test
      install:
        - HELM_VERSION=2.12.3
        - curl --retry 5 -sLO https://storage.googleapis.com/kubernetes-helm/helm-v$HELM_VERSION-linux-amd64.tar.gz
        - tar --strip-components=1 -xzvvf helm-v$HELM_VERSION-linux-amd64.tar.gz linux-amd64/helm
        - rm -f helm-v$HELM_VERSION-linux-amd64.tar.gz
        - chmod a+x helm
      script:
        - ./helm lint charts/benji-k8s
    - stage: push
      env:
        - secure: 'FQTT5peY8YF1H9E0Xp5OHgdN15sAjFw4M++k5MJisihpFDSrBoVP9hdDLht/QmJiYERXZWwWp4+kHsBwti+IEcj9cgnalZ9FLHLZpuRPaRpPKaPAoSFH/hHCq8PsrzbubGeqEDFbT6FzChmwRCvuMy5WVga8PseKbB3icEfqbp7+tN8s6wdPw0yjxycWj1KJs0DiATG+qVL8ItRi74Lda7RSSUOoXV/VdYdoTf3Whx6vT3ztSpJtt+XP/khZI+/n5asvTlcIH2xx8eTiqxljE2mAC281uo21nkrEhoOLRYhBI5KKNSUquGIS36ZOdOTNdpH868yF0fELDbVf4j1NH+T1msT1sCJvoenhBOqJeHag5eI92N9FPKvIlk3uwD9S1LE+eTE2JqS+3OFzjwT+6nCGCfIxkz/Ql7kyhgt1ihOa/VVLXLhCyYm1LRpVcpDEeAE1ThQ1Gw8BKL6Xd4Es8Rzqeff8wy68tR0FAuMlkQiByqQWtaOHfcQyu0fduM4rcKtUGpNbWCwty1AwtlPsveikM4AMFP4OJnjSsXsNjzRVtNvZ0aRt6zpWm5XkTmIOunB/x6SVI/0n8l3b+azBkhP2MBcCspIJ43Hg/VcmCEqrZi9IoDFU9ILJ7T6k3pm4q0K7PvK9nd43v112r7AC7lf7cNTrUmFFtVwKY+JcnXg='
        - secure: 'GqqjeaDmv+NQKQGpAnql+GcWZb7Io0W3L8EKMZN+ELIuXix7gDYvwrcBUjwFDpau/ZaMSzA2trZ+8+tSgYpV3pG7l4JBZJCKJ1v4vN3H2gKfJ5ju1dbFnZ3jRiTTgyAWvBUxRAza4PxD6Y65M28iAgwU5lOJ9998RbxUeKOlgoPDFm43Yjx7Hi+2DziXqcPvAzRfMQOsM8cyOQCqRKialu4sypXJ5+EcRr5QG03CT8niIFNk3ETTRLqQIJqx98+tloSHXJV+6/HW6+2D9CwxhCz4FqcrhwmzeM5yOaoVZiYQZO0GLeLMdWNE0HI5XpIu9++DD4wiXKdKnQixuwne5mUUtHaVCz106pZFnha2/aGmFTxBcdA8hiJCmw79fFTXND84IU11HX1UQjiF28v9C5TvTGd/EdGX6UwXGXbCC9xyEt2cVTvPAdMI/z7LEI29YDiRPcbWFoNoGHfl9CH2QqRoe2fzZadj4BUghdNRY28Jmx/WJLsvMkVsB2dfIBMI9+vIRGxu8XfNsTGlxE/cmsiyfGmfeu+FYK14ZKXrAfCrjFntTPcRTWAdc3H6gib7XgPDqfY90hJrEVEzGNPTmytryDRZ04Dy4MTyZ2XTwNtcxt8/b46+3t1dnZN1G2+XFThrRe+ZblUMSp17AH+zNoeqUWRykSO2qzy+ziPItoI='
      install: skip
      script:
        - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
        - GIT_PEP440_VERSION_VARIANT=miniver DOCKERFILE_PATH=images/benji/Dockerfile maint-scripts/docker-build
        - GIT_PEP440_VERSION_VARIANT=miniver DOCKERFILE_PATH=images/benji-k8s/Dockerfile maint-scripts/docker-build
