timeZone: Europe/Berlin

benji:
  image:
    registry: docker.io
    repository: elementalnet/benji-k8s
    tag: latest
    pullPolicy: Always

  resources: {}

  nodeSelector: {}

  tolerations: []

  affinity: {}

  configuration:
    configurationVersion: '1'
    databaseEngine: sqlite:////tmp/benji.sqlite
    defaultStorage: storage-1
    storages:
      - name: storage-1
        storageId: 1
        module: file
        configuration:
          path: /tmp/benji-data
    ios:
      - name: file
        module: file

  crontab:
    - name: backup-all
      schedule: "*/10 * * * *"
      command:
        - benji-backup-pvc
    - name: enforce
      schedule: "00 04 * * *"
      command:
        - benji-command
        - enforce
        - latest3,hours24,days30,months3
        - 'labels["benji-backup.me/instance"] == "benji-k8s"'
    - name: cleanup
      schedule: "00 05 * * *"
      command:
        - benji-command
        - cleanup

  # Volumes and volume mounts can be used to mount Ceph configuration and credentials, backup sources or storages into
  # the Benji container.
  volumes:
    - name: ceph-etc
      configMap:
        name: ceph-etc
        defaultMode: 0444
    - name: ceph-client-admin-keyring
      secret:
        secretName: ceph-client-admin-keyring
        defaultMode: 0444

  volumeMounts:
    - name: ceph-etc
      mountPath: /etc/ceph/ceph.conf
      subPath: ceph.conf
      readOnly: true
    - name: ceph-client-admin-keyring
      mountPath: /etc/ceph/ceph.client.admin.keyring
      subPath: ceph.client.admin.keyring
      readOnly: true

fsfreeze:
  enabled: True

  image:
    registry: docker.io
    repository: centos
    tag: 7
    pullPolicy: IfNotPresent

  resources: {}

  nodeSelector: {}

  tolerations: []

  affinity: {}

# Running the database backend on the same cluster could be dangerous!
# Please consider the implications.
postgresql:
  enabled: false
  postgresqlUsername: benji
  postgresqlDatabase: benji
  postgresqlPassword: secret

pushgateway:
  image:
    registry: docker.io
    repository: prom/pushgateway
    tag: v0.8.0
    pullPolicy: IfNotPresent
  nameOverride: pushgateway
