timeZone: Europe/Berlin

benji:
  image:
    registry: docker.io
    repository: elementalnet/benji-k8s
    tag: latest
    pullPolicy: Always

  resources: {}
  
  configuration:
    configurationVersion: '1'
    databaseEngine: sqlite:////tmp/benji.sqlite
    defaultStorage: storage-1
    storages:
      - name: storage-1
        storageId: 1
        module: file
        configuration:
          path: /tmp/benji-data
    ios:
      - name: file
        module: file

  crontab: |
    #PROM_PUSH_GATEWAY=:9091
    #BENJI_INSTANCE:-benji-k8s
    # 00  * * * * root benji-backup-pvc --all-namespaces -l 'release in (prod)'
    # 03  * * * * root benji-backup-pvc --namespace staging
    # 00 04 * * * root benji-command enforce latest3,hours24,days30,months3 'labels["benji-backup.me/instance"] == "benji-k8s"'
    # 00 05 * * * root benji-command cleanup
    
# Running the database backend on the same cluster could be dangerous!
# Please consider the implications.
postgresql:
  enabled: false
  postgresqlUsername: benji
  postgresqlDatabase: benji
  postgresqlPassword: secret

pushgateway:
  image:
    registry: docker.io
    repository: prom/pushgateway
    tag: v0.7.0
    pullPolicy: IfNotPresent

  port: 9091

  resources: {}
